### ISSUE TITLE
CSV processing requires ruby 1.9

### ISSUE THREAD

**Issue by tracyliang18** [sshaw/normalize_country#1] opened 2016-03-24 17:12 UTC
I have installed ruby1.9.1, but when running `normalize_country -f csv -t fifa -l 0 country.txt`it shows this error.

**Comment by sshaw** [comment] 2016-03-24 17:45
@tracyliang18 what's the error? :smile:

**Comment by sshaw** [comment] 2016-03-24 20:04
Oh I see, this issue's subject is the error :speak_no_evil:

**Comment by sshaw** [comment] 2016-03-24 20:14
Can you provide more info? Try the following: 

```
~/ruby/normalize_country >head -1 `which normalize_country`
#!/usr/bin/env ruby_executable_hooks
~/ruby/normalize_country >/usr/bin/env ruby_executable_hooks
```

That may provide a hint. 

Otherwise, I cannot reproduce this on various rubies >= 1.9:

```
~/ruby/normalize_country >gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.2
  - RUBY VERSION: 2.1.2 (2014-05-08 patchlevel 95) [x86_64-darwin13.0]
  - INSTALLATION DIRECTORY: /Users/sshaw/.rvm/gems/ruby-2.1.2
  - RUBY EXECUTABLE: /Users/sshaw/.rvm/rubies/ruby-2.1.2/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/sshaw/.rvm/gems/ruby-2.1.2/bin
  - SPEC CACHE DIRECTORY: /Users/sshaw/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-13
  - GEM PATHS:
     - /Users/sshaw/.rvm/gems/ruby-2.1.2
     - /Users/sshaw/.rvm/gems/ruby-2.1.2@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/sshaw/.rvm/gems/ruby-2.1.2/bin
     - /Users/sshaw/.rvm/gems/ruby-2.1.2@global/bin
     - /Users/sshaw/.rvm/rubies/ruby-2.1.2/bin
     - /Users/sshaw/.rvm/bin
     - /Users/sshaw/perl5/perlbrew/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /opt/X11/bin
     - /usr/local/MacGPG2/bin
     - /Users/sshaw/bin
     - /Users/sshaw/usr/bin
     - /usr/sbin
     - /usr/local/sbin
     - /Users/sshaw/.go/bin
     - /Users/sshaw/.cask/bin
     - /Users/sshaw/.jenv/bin
~/ruby/normalize_country >gem list normalize_country

*** LOCAL GEMS ***

normalize_country (0.1.1)
~/ruby/normalize_country >normalize_country -f csv -t fifa -l 0 $tmp
Processing /tmp/27523.tmp... normalization failed: /tmp/27523.tmp does not include a column named '0'
```

**Comment by sshaw** [comment] 2016-04-19 18:11
Closing as I cannot reproduce and no addition info has been provided by @tracyliang18.

**Closed by sshaw** 2016-04-19 18:11 UTC
Labels: invalid
